keywords:
  - 'nft'
  - 'crypto'
  - 'bitcoin'
  - 'cryptocurrency'
  # - 'btc'
  # - 'eth'
  # - 'etherum'
  # - 'blockchain'
  # - 'xrp'
  # - 'trading'
  # - 'altcoin'
  # - 'altcoins'
  # - 'binance'
  # - 'fintech'
  # - 'forex'
  # - 'mining'
  # - 'binancesmartchain'
min_faves: 100
min_retweet: 10
pages: 25
wait_time: 30